name: Local build

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ— Setup EAS local builds
        run: yarn global add eas-cli-local-build-plugin

      - name: ğŸ“¦ Build packages for mobile
        run: yarn build:mobile

      - name: ğŸ“¦ Build app locally
        working-directory: apps/mobile
        run: eas build \
          --local \
          --non-interactive \
          --output=./app-build \
          --platform=android \
          --profile=development

      - name: ğŸ’¿ Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: app-pr-${{ github.event.number }}
          path: app-build
